steps:
  # Deploy directly using gcloud run deploy with source
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bucket-list-2026'
      - '--source'
      - '.'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'
      - '--update-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,SECRET_KEY=SECRET_KEY:latest'

options:
  logging: CLOUD_LOGGING_ONLY
